@startuml
'https://plantuml.com/sequence-diagram

autonumber

DessinHTMLer -> UtilsDrawGenerator : genereRandomDessin(10)
loop 10 times
    UtilsDrawGenerator -> UtilsDrawGenerator : créé une forme aleatoire
    UtilsDrawGenerator -> UtilsDrawGenerator : ajouter la forme dans une liste
end
UtilsDrawGenerator -> UtilsDrawGenerator : creer dessin avec la liste de formes
UtilsDrawGenerator --> DessinHTMLer : dessin avec forme


UtilsDrawGenerator -> UtilsDrawGenerator : initialiser avec debutHTML
UtilsDrawGenerator -> "d:Dessin" : toHTML()
 loop chaque-forme
    "d:Dessin" -> "f:Forme" : toHTML()
    "f:Forme" --> "d:Dessin" : html de la forme
 end
"d:Dessin" --> DessinHTMLer : HTML des formes
DessinHTMLer -> DessinHTMLer : ajouter html des formes et finHTML

DessinHTMLer -> UtilsHTML :  writeHTMLToIndex(html)


@enduml